cache:
  paths:
    - isabelle-temp/
    - tmp/*/isabelle-tmp
    - apt-cache/

stages:
  - build
  - test
  - test2
  - package

build:
  stage: build
  script: make qrhl.zip
  image: aergus/latex
  artifacts:
    untracked: true
    expire_in: 30 days
    when: always

test:
  stage: test
#  dependencies:
#    - build
  script: sbt test
  artifacts:
    reports:
      junit: target/test-reports/TEST-*.xml

test-distrib:
  stage: test2
#  dependencies:
#    - build
#    - test
  script: make test-distrib

package:
  stage: package
#  dependencies:
#    - build
  script: echo Nothing to do.
  artifacts:
    paths:
      - qrhl.zip
