cache:
  paths:
    - isabelle-temp
    - tmp/*/isabelle-tmp

stages:
  - build
  - test
  - package
    
build:
  stage: build
  script: make qrhl.zip
  artifacts:
    untracked: true
    expire_in: 30 days

test:
  stage: test
  dependencies:
    - build
  script: sbt test
  artifacts:
    reports:
      junit: target/test-reports/TEST-*.xml

test-distrib:
  stage: test
  dependencies:
    - build
  script: make test-distrib

package:
  stage: package
  dependencies:
    - build
  script: echo Nothing to do.
  artifacts:
    paths:
      - qrhl.zip
