cache:
  paths:
    - isabelle-temp
    - tmp/*/isabelle-tmp

build:
  script: make qrhl.zip
  artifacts:
    untracked: true

test:
  dependencies:
    - build
  script: sbt test
  artifacts:
    reports:
      junit: target/test-reports/TEST-*.xml

test-distrib:
  dependencies:
    - build
  script: make test-distrib

package:
  dependencies:
    - build
  script: echo Nothing to do.
  artifacts:
    paths:
      - qrhl.zip
