cache:
  paths:
    - isabelle-temp/
    - tmp/*/isabelle-tmp
    - cache/

stages:
  - build
  - test
  - test2
  - package


variables:
  SBT_OPTS: "-Dsbt.global.base=cache/sbt/sbtboot -Dsbt.boot.directory=cache/sbt/boot -Dsbt.ivy.home=cache/sbt/ivy"

build:
  image: registry.gitlab.com/unruh/qrhl-tool/build-image
  stage: build
#  before_script:
#    - echo "deb https://dl.bintray.com/sbt/debian /" >> /etc/apt/sources.list.d/sbt.list
#    - apt-get -o dir::cache::archives="cache/apt" update -y
#    - apt-get -o dir::cache::archives="cache/apt" install apt-transport-https -y
#    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
#    - apt-get -o dir::cache::archives="cache/apt" update -y
#    - apt-get -o dir::cache::archives="cache/apt" install -y sbt texlive-latex-base
  script:
    - ls -lha
    - pwd
    - git status
    - git describe --tags --long --always --dirty --broken
    - git describe --always --all
    - stop here
    - make qrhl.zip
#  image: aergus/latex
  artifacts:
    untracked: true
    expire_in: 30 days
    when: always

test:
  stage: test
#  dependencies:
#    - build
  script: sbt test
  artifacts:
    reports:
      junit: target/test-reports/TEST-*.xml

test-distrib:
  stage: test2
#  dependencies:
#    - build
#    - test
  script: make test-distrib

package:
  stage: package
#  dependencies:
#    - build
  script: echo Nothing to do.
  artifacts:
    paths:
      - qrhl.zip
