language: java

before_script: scripts/travis-setup.sh

script:
  - timeout --foreground --kill-after 1m "`cat ~/remaining-time`"   ~/install/sbt test
#  - false
#  - ~/install/sbt +compile
#  - timeout -v --kill-after 1m "`cat ~/remaining-time`" ~/install/sbt -v -d -Dorg.slf4j.simpleLogger.defaultLogLevel=debug "+testOnly xxx" </dev/null | cat

cache:
  - directories:
    - $HOME/install
    - $HOME/.isabelle
    - $HOME/.cache/coursier
    - $HOME/.ivy2

jobs:
  include:
#    - os: osx
    - {os: linux, jdk: openjdk11}
#    - {os: linux, jdk: openjdk14}
