language: java

before_script: travis_wait 60 scripts/travis-setup.sh

script: ~/install/sbt -Dorg.slf4j.simpleLogger.defaultLogLevel=debug +test

cache:
  - directories:
    - $HOME/install
    - $HOME/.isabelle

jobs:
  include:
    - os: osx
#    - {os: linux, jdk: openjdk11}
#    - {os: linux, jdk: openjdk14}

