pick: random

configs:
  windows-jdk12:
    os: windows
    # We haven't configure downloading of JDKs in Windows, so we need to select the JDK that is preinstalled on Windows
    jdk: 12
  linux-jdk11:
    os: linux
    jdk: 11
  linux-jdk15:
    os: linux
    jdk: 15
  macos-jdk11:
    os: macos
    jdk: 11
  macos-jdk15:
    os: macos
    jdk: 15

defaults:
  isabelle: return "2019"
  isabellehome: |
    if os=="macos": return f"~/install/Isabelle{get('isabelle')}.app/Isabelle"
    return f"~/install/Isabelle{get('isabelle')}"
  machine_config: |
    if os=="windows": return "executor: { name: windows/default }"
    if os=="linux": return "machine: {image: ubuntu-2004:202010-01}"
    if os=="macos": return "macos: {xcode: 12.1.0}"
  sha1sum: |
    if os=="macos": return "shasum"
    return "sha1sum"
#  win_or_unix: |
#    if os=="windows": return "windows"
#    return "unix"
  jdkversionprefix: |
    if jdk=="8": return "1.8"
    if int(jdk)>=11: return str(int(jdk))
