pick: random

configs:
  linux:
    os: linux
    isabelle: 2020

defaults:
  machine_config: |
    if os=="windows": return "executor: { name: windows/default }"
    if os=="linux": return "machine: {image: ubuntu-2004:202010-01}"
