theory Universe_Instances_Bounded_Operators
  imports Bounded_Operators.Bounded_Operators Universe_Instances_Complex_Main
begin

derive universe ell2
derive universe subspace
derive universe bounded

end